name: Resume ci build #name of workflow

#when someone pushs or pulls anything trigger the code automatically
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  #what you are building on docker
  build:

    runs-on: ubuntu-latest #this is in an ubuntu container in docker

    steps:
    - uses: actions/checkout@v4 #its going to clone the repository
    - name: Build the Docker image with tag #build the docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{github.run_number}}
    - name: Build latest
      run: docker build . --file Dockerfile --tag my-image-names
    - name: Login to Docker hub
      run: docker login -u ${{secrets.REGISTORY_USERNAME}} -p ${{secrets.REGISTRY_PASS}}
    - name: Tag image
      run: docker tag my-image-name:${{github.run_number}} ${{secrets.REGISTORY_USERNAME}}/my-image-name:${{github.run_number}}
    - name: Push image
      run: docker push ${{secrets.REGISTORY_USERNAME}}/my-image-name:${{github.run_number}}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: SSH to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 3.89.101.150
          username: ${{vars.Username}}
          key: ${{secrets.KEY}}
          script: |
            docker stop resume || echo ""
            docker rm resume || echo ""
            docker run -d --name resume -p 8080:5001 ${{secrets.REGISTORY_USERNAME}}/my-image-name:${{github.run_number}}
